# Generated by Django 4.1.7 on 2023-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='2023'),
        ),
    ]
