# Generated by Django 4.1.7 on 2023-03-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denek', '0003_denek_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='denek',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
