# Generated by Django 4.1.7 on 2023-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='konu baslıgı', max_length=10, unique=True)),
                ('text_area', models.CharField(help_text='buraya yazı yazın', max_length=200)),
                ('image', models.ImageField(upload_to='blog/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_avaible', models.BooleanField(default=True)),
            ],
        ),
    ]
